preset: symfony
risky: true
enabled:
  - combine_consecutive_unsets
  - ordered_imports
  - phpdoc_order
  - php_unit_dedicate_assert
  - long_array_syntax
disabled:
  - short_array_syntax

finder :
  name    : [ "*.php", "*.twig" ]
  exclude : [ "vendor", "var" ]
  path    : [ "./" ]
